# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/airbrussh/all/airbrussh.rbi
#
# airbrussh-1.5.2

module Airbrussh
end
module Airbrussh::Colors
end
class Airbrussh::CommandFormatter < SimpleDelegator
  include Airbrussh::Colors
end
class Airbrussh::Console
end
module Airbrussh::Rake
end
class Airbrussh::Rake::Context
end
module Airbrussh::Rake::Context::Patch
end
class Airbrussh::ConsoleFormatter < SSHKit::Formatter::Abstract
  extend Forwardable
  include Airbrussh::Colors
end
class Airbrussh::LogFileFormatter < SimpleDelegator
end
class Airbrussh::Configuration
end
class Airbrussh::DelegatingFormatter
end
class Airbrussh::Formatter < Airbrussh::DelegatingFormatter
end
