# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/better_errors/all/better_errors.rbi
#
# better_errors-2.10.1

module BetterErrors
end
class BetterErrors::CodeFormatter::HTML < BetterErrors::CodeFormatter
end
class BetterErrors::CodeFormatter::Text < BetterErrors::CodeFormatter
end
class BetterErrors::CodeFormatter
end
class BetterErrors::ValueLargerThanConfiguredMaximum < StandardError
end
class BetterErrors::InspectableValue
end
module BetterErrors::ErrorPageStyle
end
class BetterErrors::ErrorPage
end
class BetterErrors::Middleware
end
class BetterErrors::ExceptionHint
end
class BetterErrors::RaisedException
end
module BetterErrors::REPL
end
class BetterErrors::StackFrame
end
class BetterErrors::Editor
end
module BetterErrors::ExceptionExtension
end
class BetterErrors::Railtie < Rails::Railtie
end
