# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/binding_of_caller/all/binding_of_caller.rbi
#
# binding_of_caller-1.0.1

module BindingOfCaller
end
module BindingOfCaller::BindingExtensions
end
class Binding
  include BindingOfCaller::BindingExtensions
end
