# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/birthday/all/birthday.rbi
#
# birthday-0.3.1

module Railslove
end
module Railslove::Acts
end
module Railslove::Acts::Birthday
  def self.included(base); end
end
module Railslove::Acts::Birthday::ClassMethods
  def acts_as_birthday(*birthday_fields); end
end
class ActiveRecord::Base
  extend Railslove::Acts::Birthday::ClassMethods
  include Railslove::Acts::Birthday
end
