# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/dead_end/all/dead_end.rbi
#
# dead_end-4.0.0

module DeadEndUnloaded
end
class DeadEndUnloaded::MiniStringIO
  def initialize(isatty: nil); end
  def isatty; end
  def puts(value = nil, **); end
  def string; end
end
