# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/email_spec/all/email_spec.rbi
#
# email_spec-2.2.2

module EmailSpec
end
module EmailSpec::Deliveries
end
class EmailSpec::AddressConverter
  extend Singleton::SingletonClassMethods
  include Singleton
end
class EmailSpec::EmailViewer
  extend EmailSpec::Deliveries
end
module EmailSpec::Helpers
  include EmailSpec::Deliveries
end
module EmailSpec::Matchers
end
class EmailSpec::Matchers::EmailMatcher
end
class EmailSpec::Matchers::ReplyTo
end
class EmailSpec::Matchers::DeliverTo < EmailSpec::Matchers::EmailMatcher
end
class EmailSpec::Matchers::DeliverFrom < EmailSpec::Matchers::EmailMatcher
end
class EmailSpec::Matchers::BccTo < EmailSpec::Matchers::EmailMatcher
end
class EmailSpec::Matchers::CcTo < EmailSpec::Matchers::EmailMatcher
end
class EmailSpec::Matchers::HaveSubject
end
class EmailSpec::Matchers::IncludeEmailWithSubject
end
class EmailSpec::Matchers::HaveBodyText
end
class EmailSpec::Matchers::HaveHeader
end
module EmailSpec::MailExt
end
class Mail::Message
  include EmailSpec::MailExt
end
class EmailSpec::TestObserver
end
class EmailSpec::CouldNotFindEmailError < StandardError
end
class EmailSpec::NoEmailAddressProvided < StandardError
end
