# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/flatpickr/all/flatpickr.rbi
#
# flatpickr-4.6.13.1

module Flatpickr
end
class Flatpickr::Engine < Rails::Engine
end
