# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/fog-aws/all/fog-aws.rbi
#
# fog-aws-3.22.0

module Fog
end
module Fog::AWS
  def self.escape(string); end
  def self.indexed_filters(filters); end
  def self.indexed_param(key, values); end
  def self.indexed_request_param(name, values); end
  def self.json_response?(response); end
  def self.parse_security_group_options(group_name, options); end
  def self.regions; end
  def self.serialize_keys(key, value, options = nil); end
  def self.signed_params(params, options = nil); end
  def self.signed_params_v4(params, headers, options = nil); end
  def self.validate_region!(region, host = nil); end
  extend Fog::Provider
end
