# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/htmlentities/all/htmlentities.rbi
#
# htmlentities-4.3.4

class HTMLEntities
end
class HTMLEntities::InstructionError < RuntimeError
end
class HTMLEntities::Encoder
end
class HTMLEntities::Decoder
end
module HTMLEntities::VERSION
end
class HTMLEntities::UnknownFlavor < RuntimeError
end
