# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/launchy/all/launchy.rbi
#
# launchy-3.0.1

module Launchy
end
module Launchy::Version
end
class Launchy::Argv
end
class Launchy::Cli
end
module Launchy::DescendantTracker
end
class Launchy::Error < StandardError
end
class Launchy::ApplicationNotFoundError < Launchy::Error
end
class Launchy::CommandNotFoundError < Launchy::Error
end
class Launchy::ArgumentError < Launchy::Error
end
class Launchy::Application
  extend Launchy::DescendantTracker
end
class Launchy::Application::Browser < Launchy::Application
end
module Launchy::Detect
end
class Launchy::Detect::HostOs
end
class Launchy::Detect::HostOsFamily
  extend Launchy::DescendantTracker
end
class Launchy::Detect::HostOsFamily::NotFoundError < Launchy::Error
end
class Launchy::Detect::HostOsFamily::Windows < Launchy::Detect::HostOsFamily
end
class Launchy::Detect::HostOsFamily::Darwin < Launchy::Detect::HostOsFamily
end
class Launchy::Detect::HostOsFamily::Nix < Launchy::Detect::HostOsFamily
end
class Launchy::Detect::HostOsFamily::Cygwin < Launchy::Detect::HostOsFamily
end
class Launchy::Detect::NixDesktopEnvironment
  extend Launchy::DescendantTracker
end
class Launchy::Detect::NixDesktopEnvironment::NotFoundError < Launchy::Error
end
class Launchy::Detect::NixDesktopEnvironment::Kde < Launchy::Detect::NixDesktopEnvironment
end
class Launchy::Detect::NixDesktopEnvironment::Gnome < Launchy::Detect::NixDesktopEnvironment
end
class Launchy::Detect::NixDesktopEnvironment::Xfce < Launchy::Detect::NixDesktopEnvironment
end
class Launchy::Detect::NixDesktopEnvironment::Xdg < Launchy::Detect::NixDesktopEnvironment
end
class Launchy::Detect::NixDesktopEnvironment::NotFound < Launchy::Detect::NixDesktopEnvironment
end
class Launchy::Runner
end
