# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/letter_opener/all/letter_opener.rbi
#
# letter_opener-1.10.0

module LetterOpener
end
class LetterOpener::Railtie < Rails::Railtie
end
class LetterOpener::DeliveryMethod
end
class LetterOpener::DeliveryMethod::InvalidOption < StandardError
end
