# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/letter_opener_web/all/letter_opener_web.rbi
#
# letter_opener_web-2.0.0

module LetterOpenerWeb
end
class LetterOpenerWeb::DeliveryMethod < LetterOpener::DeliveryMethod
end
class LetterOpenerWeb::Engine < Rails::Engine
end
class LetterOpenerWeb::Config
end
class LetterOpenerWeb::ApplicationController < ActionController::Base
  include ActionDispatch::Routing::UrlFor
  include Anonymous_Module_105
end
class LetterOpenerWeb::LettersController < LetterOpenerWeb::ApplicationController
  include Anonymous_Module_105
end
class LetterOpenerWeb::Letter
end
