# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/listen/all/listen.rbi
#
# listen-3.9.0

module Listen
end
class Listen::Options
end
class Listen::Record
end
class Listen::Record::Entry
end
class Listen::Error < RuntimeError
end
class Listen::Error::NotStarted < Listen::Error
end
class Listen::Error::SymlinkLoop < Listen::Error
end
class Listen::Error::INotifyMaxWatchesExceeded < Listen::Error
end
class Listen::Record::SymlinkDetector
end
class Listen::File
end
class Listen::Directory
end
class Listen::Change
end
class Listen::Change::Config
end
module Listen::Thread
end
module Listen::Adapter
end
class Listen::Adapter::Base
end
class Listen::Adapter::BSD < Listen::Adapter::Base
end
class Listen::Adapter::Darwin < Listen::Adapter::Base
end
class Listen::Adapter::Linux < Listen::Adapter::Base
end
class Listen::Adapter::Polling < Listen::Adapter::Base
end
class Listen::Adapter::Windows < Listen::Adapter::Base
end
class Listen::Adapter::Config
end
class Listen::Backend
  extend Forwardable
end
class Listen::Silencer
end
class Listen::Silencer::Controller
end
class Listen::QueueOptimizer
end
class Listen::QueueOptimizer::Config
end
module Listen::FSM
end
module Listen::FSM::ClassMethods
end
class Listen::FSM::State
end
module Listen::MonotonicTime
end
module Listen::Event
end
class Listen::Event::Processor
end
class Listen::Event::Processor::Stopped < RuntimeError
end
class Listen::Event::Loop
  extend Listen::FSM::ClassMethods
  include Listen::FSM
end
class Listen::Event::Queue
  extend Forwardable
end
class Listen::Event::Queue::Config
end
class Listen::Event::Config
end
class Listen::Listener
  extend Listen::FSM::ClassMethods
  include Listen::FSM
end
class Listen::Listener::Config
end
