# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: false
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/lumberjack/all/lumberjack.rbi
#
# lumberjack-1.2.10

module Lumberjack
end
module Lumberjack::Severity
end
class Lumberjack::Formatter
end
class Lumberjack::Formatter::DateTimeFormatter
end
class Lumberjack::Formatter::ExceptionFormatter
end
class Lumberjack::Formatter::IdFormatter
end
class Lumberjack::Formatter::InspectFormatter
end
class Lumberjack::Formatter::ObjectFormatter
end
class Lumberjack::Formatter::PrettyPrintFormatter
end
class Lumberjack::Formatter::StringFormatter
end
class Lumberjack::Formatter::StripFormatter
end
class Lumberjack::Formatter::StructuredFormatter
end
class Lumberjack::Formatter::StructuredFormatter::RecusiveReferenceError < StandardError
end
class Lumberjack::Formatter::TruncateFormatter
end
class Lumberjack::Context
end
class Lumberjack::LogEntry
end
class Lumberjack::Device
end
class Lumberjack::Device::Writer < Lumberjack::Device
end
class Lumberjack::Device::Writer::Buffer
end
class Lumberjack::Device::LogFile < Lumberjack::Device::Writer
end
class Lumberjack::Device::RollingLogFile < Lumberjack::Device::LogFile
end
class Lumberjack::Device::DateRollingLogFile < Lumberjack::Device::RollingLogFile
end
class Lumberjack::Device::SizeRollingLogFile < Lumberjack::Device::RollingLogFile
end
class Lumberjack::Device::Multi < Lumberjack::Device
end
class Lumberjack::Device::Null < Lumberjack::Device
end
class Lumberjack::Logger
  include Lumberjack::Severity
end
class Lumberjack::Tags
end
class Lumberjack::TagFormatter
end
module Lumberjack::TaggedLoggerSupport
end
class Lumberjack::TaggedLoggerSupport::Formatter < Anonymous_Delegator_99
  extend Forwardable
end
module Lumberjack::TaggedLogging
end
module Lumberjack::TaggedLogging::ClassMethods
end
module ActiveSupport::TaggedLogging
  include Lumberjack::TaggedLogging
end
class Lumberjack::Template
end
module Lumberjack::Rack
end
class Lumberjack::Rack::UnitOfWork
end
class Lumberjack::Rack::RequestId
end
class Lumberjack::Rack::Context
end
