# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/nenv/all/nenv.rbi
#
# nenv-0.3.0

module Nenv
end
class Nenv::Environment
end
module Nenv::Environment::Dumper::Default
end
module Nenv::Environment::Dumper
end
module Nenv::Environment::Loader::Predicate
end
module Nenv::Environment::Loader::Default
end
module Nenv::Environment::Loader
end
class Nenv::Environment::Error < ArgumentError
end
class Nenv::Environment::MethodError < Nenv::Environment::Error
end
class Nenv::Environment::AlreadyExistsError < Nenv::Environment::MethodError
end
class Nenv::AutoEnvironment < Nenv::Environment
end
module Nenv::Builder
end
