# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/notiffany/all/notiffany.rbi
#
# notiffany-0.1.3

module Notiffany
end
class Notiffany::Notifier
end
class Notiffany::Notifier::Base
end
class Notiffany::Notifier::Base::UnavailableError < RuntimeError
end
class Notiffany::Notifier::Base::RequireFailed < Notiffany::Notifier::Base::UnavailableError
end
class Notiffany::Notifier::Base::UnsupportedPlatform < Notiffany::Notifier::Base::UnavailableError
end
class Notiffany::Notifier::Emacs < Notiffany::Notifier::Base
end
class Notiffany::Notifier::Emacs::Client
end
class Notiffany::Notifier::Emacs::Client::Elisp < ERB
end
class Notiffany::Notifier::File < Notiffany::Notifier::Base
end
class Notiffany::Notifier::GNTP < Notiffany::Notifier::Base
end
class Notiffany::Notifier::Growl < Notiffany::Notifier::Base
end
class Notiffany::Notifier::Libnotify < Notiffany::Notifier::Base
end
class Notiffany::Notifier::NotifySend < Notiffany::Notifier::Base
end
class Notiffany::Notifier::Notifu < Notiffany::Notifier::Base
end
class Notiffany::Notifier::TerminalNotifier < Notiffany::Notifier::Base
end
class Notiffany::Notifier::TerminalTitle < Notiffany::Notifier::Base
end
class Notiffany::Notifier::Tmux < Notiffany::Notifier::Base
end
class Notiffany::Notifier::Tmux::Client
end
class Notiffany::Notifier::Tmux::Session
end
class Notiffany::Notifier::Tmux::Notification
end
class Notiffany::Notifier::Tmux::Error < RuntimeError
end
class Notiffany::Notifier::YamlEnvStorage < Nenv::Environment
end
class Notiffany::Notifier::Detected
end
class Notiffany::Notifier::Detected::NoneAvailableError < RuntimeError
end
class Notiffany::Notifier::Detected::UnknownNotifier < RuntimeError
end
class Notiffany::Notifier::Config
end
class Notiffany::Notifier::Env < Nenv::Environment
end
class Notiffany::Notifier::NotServer < RuntimeError
end
