# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/pry-stack_explorer/all/pry-stack_explorer.rbi
#
# pry-stack_explorer-0.6.1

module PryStackExplorer
end
module PryStackExplorer::FrameHelpers
end
class PryStackExplorer::FrameManager
  include Enumerable
end
class PryStackExplorer::WhenStartedHook
  include Pry::Helpers::BaseHelpers
end
