# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/rails-i18n/all/rails-i18n.rbi
#
# rails-i18n-7.0.9

module RailsI18n
  def self.enabled_modules; end
  def self.enabled_modules=(other); end
end
class RailsI18n::Railtie < Rails::Railtie
  def self.add(pattern); end
  def self.init_pluralization_module; end
  def self.pattern_from(args); end
end
