# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/rubocop-rails/all/rubocop-rails.rbi
#
# rubocop-rails-2.25.1

module RuboCop
end
module RuboCop::Rails
end
module RuboCop::Rails::Version
end
module RuboCop::Rails::Inject
end
module RuboCop::Rails::SchemaLoader
  extend RuboCop::Rails::SchemaLoader
end
class RuboCop::Rails::SchemaLoader::Schema
end
class RuboCop::Rails::SchemaLoader::Table
end
class RuboCop::Rails::SchemaLoader::Column
end
class RuboCop::Rails::SchemaLoader::Index
end
class RuboCop::Rails::SchemaLoader::AddIndex < RuboCop::Rails::SchemaLoader::Index
end
module RuboCop::Cop
end
module RuboCop::Cop::ActiveRecordHelper
  extend RuboCop::AST::NodePattern::Macros
end
module RuboCop::Cop::ActiveRecordMigrationsHelper
  extend RuboCop::AST::NodePattern::Macros
end
module RuboCop::Cop::ClassSendNodeHelper
end
module RuboCop::Cop::DatabaseTypeResolvable
end
module RuboCop::Cop::EnforceSuperclass
end
module RuboCop::Cop::IndexMethod
end
module RuboCop::Cop::MigrationsHelper
  extend RuboCop::AST::NodePattern::Macros
end
module RuboCop::Cop::TargetRailsVersion
end
module RuboCop::Cop::Rails
end
class RuboCop::Cop::Rails::ActionControllerFlashBeforeRender < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
end
class RuboCop::Cop::Rails::ActionControllerTestCase < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
  extend RuboCop::Cop::TargetRailsVersion
end
class RuboCop::Cop::Rails::ActionFilter < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
  include RuboCop::Cop::ConfigurableEnforcedStyle
end
class RuboCop::Cop::Rails::ActionOrder < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
  include RuboCop::Cop::DefNode
  include RuboCop::Cop::RangeHelp
  include RuboCop::Cop::VisibilityHelp
end
class RuboCop::Cop::Rails::ActiveRecordAliases < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
end
class RuboCop::Cop::Rails::ActiveRecordCallbacksOrder < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
end
class RuboCop::Cop::Rails::ActiveRecordOverride < RuboCop::Cop::Base
end
class RuboCop::Cop::Rails::ActiveSupportAliases < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
end
class RuboCop::Cop::Rails::ActiveSupportOnLoad < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
end
class RuboCop::Cop::Rails::AddColumnIndex < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
  include RuboCop::Cop::RangeHelp
end
class RuboCop::Cop::Rails::AfterCommitOverride < RuboCop::Cop::Base
  include RuboCop::Cop::ClassSendNodeHelper
end
class RuboCop::Cop::Rails::ApplicationController < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
  include RuboCop::Cop::EnforceSuperclass
end
class RuboCop::Cop::Rails::ApplicationJob < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
  extend RuboCop::Cop::TargetRailsVersion
  include RuboCop::Cop::EnforceSuperclass
end
class RuboCop::Cop::Rails::ApplicationMailer < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
  extend RuboCop::Cop::TargetRailsVersion
  include RuboCop::Cop::EnforceSuperclass
end
class RuboCop::Cop::Rails::ApplicationRecord < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
  extend RuboCop::Cop::TargetRailsVersion
  include RuboCop::Cop::EnforceSuperclass
end
class RuboCop::Cop::Rails::ArelStar < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
end
class RuboCop::Cop::Rails::AssertNot < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
end
class RuboCop::Cop::Rails::AttributeDefaultBlockValue < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
end
class RuboCop::Cop::Rails::BelongsTo < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
  extend RuboCop::Cop::TargetRailsVersion
end
class RuboCop::Cop::Rails::Blank < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
end
class RuboCop::Cop::Rails::BulkChangeTable < RuboCop::Cop::Base
  include RuboCop::Cop::DatabaseTypeResolvable
end
class RuboCop::Cop::Rails::BulkChangeTable::AlterMethodsRecorder
end
class RuboCop::Cop::Rails::CompactBlank < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
  extend RuboCop::Cop::TargetRailsVersion
  include RuboCop::Cop::RangeHelp
end
class RuboCop::Cop::Rails::ContentTag < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
  extend RuboCop::Cop::TargetRailsVersion
  include RuboCop::Cop::RangeHelp
end
class RuboCop::Cop::Rails::CreateTableWithTimestamps < RuboCop::Cop::Base
  include RuboCop::Cop::ActiveRecordMigrationsHelper
end
class RuboCop::Cop::Rails::DangerousColumnNames < RuboCop::Cop::Base
end
class RuboCop::Cop::Rails::Date < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
  include RuboCop::Cop::ConfigurableEnforcedStyle
end
class RuboCop::Cop::Rails::DefaultScope < RuboCop::Cop::Base
end
class RuboCop::Cop::Rails::Delegate < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
  include RuboCop::Cop::VisibilityHelp
end
class RuboCop::Cop::Rails::DelegateAllowBlank < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
end
class RuboCop::Cop::Rails::DeprecatedActiveModelErrorsMethods < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
  include RuboCop::Cop::RangeHelp
end
class RuboCop::Cop::Rails::DotSeparatedKeys < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
  include RuboCop::Cop::RangeHelp
end
class RuboCop::Cop::Rails::DuplicateAssociation < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
  include RuboCop::Cop::ActiveRecordHelper
  include RuboCop::Cop::ClassSendNodeHelper
  include RuboCop::Cop::RangeHelp
end
class RuboCop::Cop::Rails::DuplicateScope < RuboCop::Cop::Base
  include RuboCop::Cop::ClassSendNodeHelper
end
class RuboCop::Cop::Rails::DurationArithmetic < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
end
class RuboCop::Cop::Rails::DynamicFindBy < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
  include RuboCop::Cop::ActiveRecordHelper
end
class RuboCop::Cop::Rails::EagerEvaluationLogMessage < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
end
class RuboCop::Cop::Rails::EnumHash < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
end
class RuboCop::Cop::Rails::EnumUniqueness < RuboCop::Cop::Base
  include RuboCop::Cop::Duplication
end
class RuboCop::Cop::Rails::EnvLocal < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
  extend RuboCop::Cop::TargetRailsVersion
end
class RuboCop::Cop::Rails::EnvironmentComparison < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
end
class RuboCop::Cop::Rails::EnvironmentVariableAccess < RuboCop::Cop::Base
end
class RuboCop::Cop::Rails::Exit < RuboCop::Cop::Base
  include RuboCop::Cop::ConfigurableEnforcedStyle
end
class RuboCop::Cop::Rails::ExpandedDateRange < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
  extend RuboCop::Cop::TargetRailsVersion
end
class RuboCop::Cop::Rails::FilePath < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
  include RuboCop::Cop::ConfigurableEnforcedStyle
  include RuboCop::Cop::RangeHelp
end
class RuboCop::Cop::Rails::FindBy < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
  include RuboCop::Cop::RangeHelp
end
class RuboCop::Cop::Rails::FindById < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
  include RuboCop::Cop::RangeHelp
end
class RuboCop::Cop::Rails::FindEach < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
  include RuboCop::Cop::ActiveRecordHelper
  include RuboCop::Cop::AllowedMethods
  include RuboCop::Cop::AllowedPattern
end
class RuboCop::Cop::Rails::FreezeTime < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
  extend RuboCop::Cop::TargetRailsVersion
end
class RuboCop::Cop::Rails::HasAndBelongsToMany < RuboCop::Cop::Base
end
class RuboCop::Cop::Rails::HasManyOrHasOneDependent < RuboCop::Cop::Base
end
class RuboCop::Cop::Rails::HelperInstanceVariable < RuboCop::Cop::Base
end
class RuboCop::Cop::Rails::HttpPositionalArguments < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
  extend RuboCop::Cop::TargetRailsVersion
  include RuboCop::Cop::RangeHelp
end
class RuboCop::Cop::Rails::HttpStatus < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
  include RuboCop::Cop::ConfigurableEnforcedStyle
end
class RuboCop::Cop::Rails::HttpStatus::SymbolicStyleChecker
end
class RuboCop::Cop::Rails::HttpStatus::NumericStyleChecker
end
class RuboCop::Cop::Rails::I18nLazyLookup < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
  include RuboCop::Cop::ConfigurableEnforcedStyle
  include RuboCop::Cop::VisibilityHelp
end
class RuboCop::Cop::Rails::I18nLocaleAssignment < RuboCop::Cop::Base
end
class RuboCop::Cop::Rails::I18nLocaleTexts < RuboCop::Cop::Base
end
class RuboCop::Cop::Rails::IgnoredColumnsAssignment < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
end
class RuboCop::Cop::Rails::IgnoredSkipActionFilterOption < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
  include RuboCop::Cop::RangeHelp
end
class RuboCop::Cop::Rails::IndexBy < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
  include RuboCop::Cop::IndexMethod
end
class RuboCop::Cop::Rails::IndexWith < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
  extend RuboCop::Cop::TargetRailsVersion
  include RuboCop::Cop::IndexMethod
end
class RuboCop::Cop::Rails::Inquiry < RuboCop::Cop::Base
end
class RuboCop::Cop::Rails::InverseOf < RuboCop::Cop::Base
end
class RuboCop::Cop::Rails::LexicallyScopedActionFilter < RuboCop::Cop::Base
end
class RuboCop::Cop::Rails::LinkToBlank < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
end
class RuboCop::Cop::Rails::MailerName < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
end
class RuboCop::Cop::Rails::MatchRoute < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
end
class RuboCop::Cop::Rails::MigrationClassName < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
  include RuboCop::Cop::MigrationsHelper
end
class RuboCop::Cop::Rails::NegateInclude < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
end
class RuboCop::Cop::Rails::NotNullColumn < RuboCop::Cop::Base
  include RuboCop::Cop::DatabaseTypeResolvable
end
class RuboCop::Cop::Rails::OrderById < RuboCop::Cop::Base
  include RuboCop::Cop::RangeHelp
end
class RuboCop::Cop::Rails::Output < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
  include RuboCop::Cop::RangeHelp
end
class RuboCop::Cop::Rails::OutputSafety < RuboCop::Cop::Base
end
class RuboCop::Cop::Rails::Pick < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
  extend RuboCop::Cop::TargetRailsVersion
end
class RuboCop::Cop::Rails::Pluck < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
  extend RuboCop::Cop::TargetRailsVersion
end
class RuboCop::Cop::Rails::PluckId < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
  include RuboCop::Cop::ActiveRecordHelper
  include RuboCop::Cop::RangeHelp
end
class RuboCop::Cop::Rails::PluckInWhere < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
  include RuboCop::Cop::ActiveRecordHelper
  include RuboCop::Cop::ConfigurableEnforcedStyle
end
class RuboCop::Cop::Rails::PluralizationGrammar < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
end
class RuboCop::Cop::Rails::Presence < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
  include RuboCop::Cop::RangeHelp
end
class RuboCop::Cop::Rails::Present < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
end
class RuboCop::Cop::Rails::RakeEnvironment < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
end
class RuboCop::Cop::Rails::ReadWriteAttribute < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
end
module RuboCop::Cop::Rails::AllowedReceivers
end
class RuboCop::Cop::Rails::RedundantActiveRecordAllMethod < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
  include RuboCop::Cop::ActiveRecordHelper
  include RuboCop::Cop::Rails::AllowedReceivers
  include RuboCop::Cop::RangeHelp
end
class RuboCop::Cop::Rails::RedundantAllowNil < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
  include RuboCop::Cop::RangeHelp
end
class RuboCop::Cop::Rails::RedundantForeignKey < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
  include RuboCop::Cop::RangeHelp
end
class RuboCop::Cop::Rails::RedundantPresenceValidationOnBelongsTo < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
  extend RuboCop::Cop::TargetRailsVersion
  include RuboCop::Cop::RangeHelp
end
class RuboCop::Cop::Rails::RedundantReceiverInWithOptions < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
  include RuboCop::Cop::RangeHelp
end
class RuboCop::Cop::Rails::RedundantTravelBack < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
  extend RuboCop::Cop::TargetRailsVersion
  include RuboCop::Cop::RangeHelp
end
class RuboCop::Cop::Rails::ReflectionClassName < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
end
class RuboCop::Cop::Rails::RefuteMethods < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
  include RuboCop::Cop::ConfigurableEnforcedStyle
end
class RuboCop::Cop::Rails::RelativeDateConstant < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
  include RuboCop::Cop::RangeHelp
end
class RuboCop::Cop::Rails::RenderInline < RuboCop::Cop::Base
end
class RuboCop::Cop::Rails::RenderPlainText < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
end
class RuboCop::Cop::Rails::RequestReferer < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
  include RuboCop::Cop::ConfigurableEnforcedStyle
end
class RuboCop::Cop::Rails::RequireDependency < RuboCop::Cop::Base
  extend RuboCop::Cop::TargetRailsVersion
end
class RuboCop::Cop::Rails::ResponseParsedBody < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
  extend RuboCop::Cop::TargetRailsVersion
end
class RuboCop::Cop::Rails::ReversibleMigration < RuboCop::Cop::Base
  include RuboCop::Cop::MigrationsHelper
end
class RuboCop::Cop::Rails::ReversibleMigrationMethodDefinition < RuboCop::Cop::Base
  include RuboCop::Cop::MigrationsHelper
end
class RuboCop::Cop::Rails::RootJoinChain < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
  include RuboCop::Cop::RangeHelp
end
class RuboCop::Cop::Rails::RootPathnameMethods < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
  include RuboCop::Cop::RangeHelp
end
class RuboCop::Cop::Rails::RootPublicPath < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
end
class RuboCop::Cop::Rails::SafeNavigation < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
  extend RuboCop::Cop::TargetRubyVersion
  include RuboCop::Cop::RangeHelp
end
class RuboCop::Cop::Rails::SafeNavigationWithBlank < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
end
class RuboCop::Cop::Rails::SaveBang < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
  include RuboCop::Cop::NegativeConditional
end
class RuboCop::Cop::Rails::SchemaComment < RuboCop::Cop::Base
  include RuboCop::Cop::ActiveRecordMigrationsHelper
end
class RuboCop::Cop::Rails::ScopeArgs < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
end
class RuboCop::Cop::Rails::SelectMap < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
end
class RuboCop::Cop::Rails::ShortI18n < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
  include RuboCop::Cop::ConfigurableEnforcedStyle
end
class RuboCop::Cop::Rails::SkipsModelValidations < RuboCop::Cop::Base
end
class RuboCop::Cop::Rails::SquishedSQLHeredocs < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
  include RuboCop::Cop::Heredoc
end
class RuboCop::Cop::Rails::StripHeredoc < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
  extend RuboCop::Cop::TargetRubyVersion
end
class RuboCop::Cop::Rails::TableNameAssignment < RuboCop::Cop::Base
  include RuboCop::Cop::ActiveRecordHelper
end
class RuboCop::Cop::Rails::ThreeStateBooleanColumn < RuboCop::Cop::Base
end
class RuboCop::Cop::Rails::TimeZone < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
  include RuboCop::Cop::ConfigurableEnforcedStyle
end
class RuboCop::Cop::Rails::TimeZoneAssignment < RuboCop::Cop::Base
end
class RuboCop::Cop::Rails::ToFormattedS < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
  extend RuboCop::Cop::TargetRailsVersion
  include RuboCop::Cop::ConfigurableEnforcedStyle
end
class RuboCop::Cop::Rails::ToSWithArgument < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
  extend RuboCop::Cop::TargetRailsVersion
end
class RuboCop::Cop::Rails::TopLevelHashWithIndifferentAccess < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
  extend RuboCop::Cop::TargetRailsVersion
end
class RuboCop::Cop::Rails::TransactionExitStatement < RuboCop::Cop::Base
end
class RuboCop::Cop::Rails::UniqBeforePluck < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
  include RuboCop::Cop::ConfigurableEnforcedStyle
  include RuboCop::Cop::RangeHelp
end
class RuboCop::Cop::Rails::UniqueValidationWithoutIndex < RuboCop::Cop::Base
  include RuboCop::Cop::ActiveRecordHelper
end
class RuboCop::Cop::Rails::UnknownEnv < RuboCop::Cop::Base
end
class RuboCop::Cop::Rails::UnusedIgnoredColumns < RuboCop::Cop::Base
  include RuboCop::Cop::ActiveRecordHelper
end
class RuboCop::Cop::Rails::UnusedRenderContent < RuboCop::Cop::Base
  include RuboCop::Cop::RangeHelp
end
class RuboCop::Cop::Rails::Validation < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
end
class RuboCop::Cop::Rails::WhereEquals < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
  include RuboCop::Cop::RangeHelp
end
class RuboCop::Cop::Rails::WhereExists < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
  include RuboCop::Cop::ConfigurableEnforcedStyle
end
class RuboCop::Cop::Rails::WhereMissing < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
  extend RuboCop::Cop::TargetRailsVersion
  include RuboCop::Cop::RangeHelp
end
class RuboCop::Cop::Rails::WhereNot < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
  include RuboCop::Cop::RangeHelp
end
class RuboCop::Cop::Rails::WhereNotWithMultipleConditions < RuboCop::Cop::Base
end
class RuboCop::Cop::Rails::WhereRange < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
  extend RuboCop::Cop::TargetRailsVersion
  extend RuboCop::Cop::TargetRubyVersion
  include RuboCop::Cop::RangeHelp
end
