# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/ruby-lsp-rails/all/ruby-lsp-rails.rbi
#
# ruby-lsp-rails-0.3.11

module RubyLsp
end
module RubyLsp::Rails
end
class RubyLsp::Rails::Railtie < Rails::Railtie
end
