# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/sidekiq/all/sidekiq.rbi
#
# sidekiq-7.3.0

module Sidekiq
  def self.configure_client; end
  def self.configure_embed(&block); end
  def self.configure_server(&block); end
  def self.default_configuration; end
  def self.default_job_options; end
  def self.default_job_options=(hash); end
  def self.dump_json(object); end
  def self.ent?; end
  def self.freeze!; end
  def self.load_json(string); end
  def self.logger; end
  def self.pro?; end
  def self.redis(&block); end
  def self.redis_pool; end
  def self.server?; end
  def self.strict_args!(mode = nil); end
  def self.transactional_push!; end
end
class Sidekiq::RedisClientAdapter
  def client_opts(options); end
  def initialize(options); end
  def new_client; end
end
module Sidekiq::RedisClientAdapter::CompatMethods
  def bitfield(*args, **kwargs); end
  def bitfield_ro(*args, **kwargs); end
  def del(*args, **kwargs); end
  def evalsha(sha, keys, argv); end
  def exists(*args, **kwargs); end
  def expire(*args, **kwargs); end
  def flushdb(*args, **kwargs); end
  def get(*args, **kwargs); end
  def hdel(*args, **kwargs); end
  def hget(*args, **kwargs); end
  def hgetall(*args, **kwargs); end
  def hincrby(*args, **kwargs); end
  def hlen(*args, **kwargs); end
  def hmget(*args, **kwargs); end
  def hset(*args, **kwargs); end
  def hsetnx(*args, **kwargs); end
  def incr(*args, **kwargs); end
  def incrby(*args, **kwargs); end
  def info; end
  def lindex(*args, **kwargs); end
  def llen(*args, **kwargs); end
  def lmove(*args, **kwargs); end
  def lpop(*args, **kwargs); end
  def lpush(*args, **kwargs); end
  def lrange(*args, **kwargs); end
  def lrem(*args, **kwargs); end
  def method_missing(*args, **, &block); end
  def mget(*args, **kwargs); end
  def mset(*args, **kwargs); end
  def ping(*args, **kwargs); end
  def pttl(*args, **kwargs); end
  def publish(*args, **kwargs); end
  def respond_to_missing?(name, include_private = nil); end
  def rpop(*args, **kwargs); end
  def rpush(*args, **kwargs); end
  def sadd(*args, **kwargs); end
  def scard(*args, **kwargs); end
  def script(*args, **kwargs); end
  def set(*args, **kwargs); end
  def sismember(*args, **kwargs); end
  def smembers(*args, **kwargs); end
  def srem(*args, **kwargs); end
  def ttl(*args, **kwargs); end
  def type(*args, **kwargs); end
  def unlink(*args, **kwargs); end
  def zadd(*args, **kwargs); end
  def zcard(*args, **kwargs); end
  def zincrby(*args, **kwargs); end
  def zrange(*args, **kwargs); end
  def zrem(*args, **kwargs); end
  def zremrangebyrank(*args, **kwargs); end
  def zremrangebyscore(*args, **kwargs); end
end
class Sidekiq::RedisClientAdapter::CompatClient < RedisClient::Decorator::Client
  def config; end
  include Sidekiq::RedisClientAdapter::CompatMethods
end
class Sidekiq::RedisClientAdapter::CompatClient::Pipeline < RedisClient::Decorator::Pipeline
  include Sidekiq::RedisClientAdapter::CompatMethods
end
module Sidekiq::RedisConnection
  def self.create(options = nil); end
  def self.deep_symbolize_keys(object); end
  def self.determine_redis_provider; end
  def self.scrub(options); end
end
class Sidekiq::Config
  def [](*args, **, &block); end
  def []=(*args, **, &block); end
  def average_scheduled_poll_interval=(interval); end
  def capsule(name); end
  def capsules; end
  def client_middleware; end
  def concurrency; end
  def concurrency=(val); end
  def death_handlers; end
  def default_capsule(&block); end
  def dig(*args, **, &block); end
  def error_handlers; end
  def fetch(*args, **, &block); end
  def handle_exception(ex, ctx = nil); end
  def has_key?(*args, **, &block); end
  def initialize(options = nil); end
  def key?(*args, **, &block); end
  def local_redis_pool; end
  def logger; end
  def logger=(logger); end
  def lookup(name, default_class = nil); end
  def merge!(*args, **, &block); end
  def new_redis_pool(size, name = nil); end
  def on(event, &block); end
  def parameter_size(handler); end
  def queues; end
  def queues=(val); end
  def redis; end
  def redis=(hash); end
  def redis_info; end
  def redis_pool; end
  def register(name, instance); end
  def server_middleware; end
  def to_json(*); end
  def total_concurrency; end
  extend Forwardable
end
module Sidekiq::Context
  def self.add(k, v); end
  def self.current; end
  def self.with(hash); end
end
module Sidekiq::LoggingUtils
  def debug?; end
  def error?; end
  def fatal?; end
  def info?; end
  def level; end
  def local_level; end
  def local_level=(level); end
  def log_at(level); end
  def warn?; end
end
class Sidekiq::Logger < Logger
  include Sidekiq::LoggingUtils
end
module Sidekiq::Logger::Formatters
end
class Sidekiq::Logger::Formatters::Base < Logger::Formatter
  def ctx; end
  def format_context; end
  def tid; end
end
class Sidekiq::Logger::Formatters::Pretty < Sidekiq::Logger::Formatters::Base
  def call(severity, time, program_name, message); end
end
class Sidekiq::Logger::Formatters::WithoutTimestamp < Sidekiq::Logger::Formatters::Pretty
  def call(severity, time, program_name, message); end
end
class Sidekiq::Logger::Formatters::JSON < Sidekiq::Logger::Formatters::Base
  def call(severity, time, program_name, message); end
end
module Sidekiq::ServerMiddleware
  def config; end
  def config=(arg0); end
  def logger; end
  def redis(&block); end
  def redis_pool; end
end
module Sidekiq::Middleware
end
class Sidekiq::Middleware::Chain
  def add(klass, *args); end
  def clear; end
  def copy_for(capsule); end
  def each(&block); end
  def empty?; end
  def entries; end
  def exists?(klass); end
  def include?(klass); end
  def initialize(config = nil); end
  def insert_after(oldklass, newklass, *args); end
  def insert_before(oldklass, newklass, *args); end
  def invoke(*args, &block); end
  def prepend(klass, *args); end
  def remove(klass); end
  def retrieve; end
  def traverse(chain, index, args, &block); end
  include Enumerable
end
class Sidekiq::Middleware::Entry
  def initialize(config, klass, *args); end
  def klass; end
  def make_new; end
end
module Sidekiq::JobUtil
  def json_unsafe?(item); end
  def normalize_item(item); end
  def normalized_hash(item_class); end
  def validate(item); end
  def verify_json(item); end
end
class Sidekiq::Client
  def atomic_push(conn, payloads); end
  def initialize(*args, **kwargs); end
  def middleware(&block); end
  def push(item); end
  def push_bulk(items); end
  def raw_push(payloads); end
  def redis_pool; end
  def redis_pool=(arg0); end
  def self.enqueue(klass, *args); end
  def self.enqueue_in(interval, klass, *args); end
  def self.enqueue_to(queue, klass, *args); end
  def self.enqueue_to_in(queue, interval, klass, *args); end
  def self.push(item); end
  def self.push_bulk(*, **, &); end
  def self.via(pool); end
  include Sidekiq::JobUtil
end
class Sidekiq::TransactionAwareClient
  def batching?; end
  def initialize(pool: nil, config: nil); end
  def push(item); end
  def push_bulk(items); end
end
module Sidekiq::Job
  def _context; end
  def _context=(arg0); end
  def interrupted?; end
  def jid; end
  def jid=(arg0); end
  def logger; end
  def self.included(base); end
end
module Sidekiq::Job::Options
  def self.included(base); end
end
module Sidekiq::Job::Options::ClassMethods
  def get_sidekiq_options; end
  def sidekiq_class_attribute(*attrs); end
  def sidekiq_options(opts = nil); end
  def sidekiq_retries_exhausted(&block); end
  def sidekiq_retry_in(&block); end
end
class Sidekiq::Job::Setter
  def at(interval); end
  def initialize(klass, opts); end
  def perform_async(*args); end
  def perform_at(interval, *args); end
  def perform_bulk(args, batch_size: nil); end
  def perform_in(interval, *args); end
  def perform_inline(*args); end
  def perform_sync(*args); end
  def set(options); end
  include Sidekiq::JobUtil
end
module Sidekiq::Job::ClassMethods
  def build_client; end
  def client_push(item); end
  def delay(*args); end
  def delay_for(*args); end
  def delay_until(*args); end
  def perform_async(*args); end
  def perform_at(interval, *args); end
  def perform_bulk(*args, **kwargs); end
  def perform_in(interval, *args); end
  def perform_inline(*args); end
  def perform_sync(*args); end
  def queue_as(q); end
  def set(options); end
  def sidekiq_options(opts = nil); end
end
module Sidekiq::Job::Iterable
  def around_iteration; end
  def assert_enumerator!(enum); end
  def build_enumerator(*); end
  def cleanup; end
  def each_iteration(*); end
  def fetch_previous_iteration_state; end
  def flush_state; end
  def handle_completed(completed); end
  def initialize; end
  def iterate_with_enumerator(enumerator, arguments); end
  def iteration_key; end
  def on_complete; end
  def on_resume; end
  def on_start; end
  def on_stop; end
  def perform(*arguments); end
  def reenqueue_iteration_job; end
  def self.included(base); end
  include Sidekiq::Job::Iterable::Enumerators
end
class Sidekiq::Job::Iterable::ActiveRecordEnumerator
  def batches; end
  def initialize(relation, cursor: nil, **options); end
  def records; end
  def relations; end
  def relations_size; end
end
class Sidekiq::Job::Iterable::CsvEnumerator
  def batches(cursor:, batch_size: nil); end
  def count_of_rows_in_file; end
  def initialize(csv); end
  def rows(cursor:); end
end
module Sidekiq::Job::Iterable::Enumerators
  def active_record_batches_enumerator(relation, cursor:, **options); end
  def active_record_records_enumerator(relation, cursor:, **options); end
  def active_record_relations_enumerator(relation, cursor:, **options); end
  def array_enumerator(array, cursor:); end
  def csv_batches_enumerator(csv, cursor:, **options); end
  def csv_enumerator(csv, cursor:); end
end
class Sidekiq::Job::Interrupted < RuntimeError
end
module Sidekiq::Job::Iterable::ClassMethods
  def method_added(method_name); end
end
module Sidekiq::IterableJob
  def self.included(base); end
end
class Sidekiq::Rails < Rails::Engine
end
class Sidekiq::Rails::Reloader
  def call; end
  def initialize(app = nil); end
  def inspect; end
  def to_hash; end
end
class Sidekiq::Shutdown < Interrupt
end
