# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/site_ruby/all/site_ruby.rbi
#
# site_ruby-3.3.0

module Gem::DefaultUserInteraction
  def self.ui; end
  def self.ui=(new_ui); end
  def self.use_ui(new_ui); end
  def ui; end
  def ui=(new_ui); end
  def use_ui(new_ui, &block); end
  include Gem::Text
end
module Gem::UserInteraction
  def alert(statement, question = nil); end
  def alert_error(statement, question = nil); end
  def alert_warning(statement, question = nil); end
  def ask(question); end
  def ask_for_password(prompt); end
  def ask_yes_no(question, default = nil); end
  def choose_from_list(question, list); end
  def say(statement = nil); end
  def terminate_interaction(exit_code = nil); end
  def verbose(msg = nil); end
  include Gem::DefaultUserInteraction
end
class Gem::StreamUI
  def _gets_noecho; end
  def alert(statement, question = nil); end
  def alert_error(statement, question = nil); end
  def alert_warning(statement, question = nil); end
  def ask(question); end
  def ask_for_password(question); end
  def ask_yes_no(question, default = nil); end
  def backtrace(exception); end
  def choose_from_list(question, list); end
  def close; end
  def download_reporter(*args); end
  def errs; end
  def initialize(in_stream, out_stream, err_stream = nil, usetty = nil); end
  def ins; end
  def outs; end
  def progress_reporter(*args); end
  def require_io_console; end
  def say(statement = nil); end
  def terminate_interaction(status = nil); end
  def tty?; end
  extend Gem::Deprecate
end
class Gem::StreamUI::SilentProgressReporter
  def count; end
  def done; end
  def initialize(out_stream, size, initial_message, terminal_message = nil); end
  def updated(message); end
end
class Gem::StreamUI::SimpleProgressReporter
  def count; end
  def done; end
  def initialize(out_stream, size, initial_message, terminal_message = nil); end
  def updated(message); end
  include Gem::DefaultUserInteraction
end
class Gem::StreamUI::VerboseProgressReporter
  def count; end
  def done; end
  def initialize(out_stream, size, initial_message, terminal_message = nil); end
  def updated(message); end
  include Gem::DefaultUserInteraction
end
class Gem::StreamUI::SilentDownloadReporter
  def done; end
  def fetch(filename, filesize); end
  def initialize(out_stream, *args); end
  def update(current); end
end
class Gem::StreamUI::ThreadedDownloadReporter
  def done; end
  def fetch(file_name, *args); end
  def file_name; end
  def initialize(out_stream, *args); end
  def locked_puts(message); end
  def update(bytes); end
end
class Gem::ConsoleUI < Gem::StreamUI
  def initialize; end
end
class Gem::SilentUI < Gem::StreamUI
  def close; end
  def download_reporter(*args); end
  def initialize; end
  def progress_reporter(*args); end
end
class Gem::SilentUI::NullIO
  def flush; end
  def gets(*args); end
  def print(*args); end
  def puts(*args); end
  def tty?; end
end
module Gem::URI
  def self._decode_uri_component(regexp, str, enc); end
  def self._encode_uri_component(regexp, table, str, enc); end
  def self.decode_uri_component(str, enc = nil); end
  def self.decode_www_form(str, enc = nil, separator: nil, use__charset_: nil, isindex: nil); end
  def self.decode_www_form_component(str, enc = nil); end
  def self.encode_uri_component(str, enc = nil); end
  def self.encode_www_form(enum, enc = nil); end
  def self.encode_www_form_component(str, enc = nil); end
  def self.extract(str, schemes = nil, &block); end
  def self.for(scheme, *arguments, default: nil); end
  def self.get_encoding(label); end
  def self.join(*str); end
  def self.parse(uri); end
  def self.regexp(schemes = nil); end
  def self.register_scheme(scheme, klass); end
  def self.scheme_list; end
  def self.split(uri); end
  include Gem::URI::RFC2396_REGEXP
end
module Gem::URI::RFC2396_REGEXP
end
module Gem::URI::RFC2396_REGEXP::PATTERN
end
class Gem::URI::RFC2396_Parser
  def convert_to_uri(uri); end
  def escape(str, unsafe = nil); end
  def extract(str, schemes = nil); end
  def initialize(opts = nil); end
  def initialize_pattern(opts = nil); end
  def initialize_regexp(pattern); end
  def inspect; end
  def join(*uris); end
  def make_regexp(schemes = nil); end
  def parse(uri); end
  def pattern; end
  def regexp; end
  def split(uri); end
  def unescape(str, escaped = nil); end
  include Gem::URI::RFC2396_REGEXP
end
class Gem::URI::RFC3986_Parser
  def convert_to_uri(uri); end
  def default_regexp; end
  def initialize; end
  def inspect; end
  def join(*uris); end
  def parse(uri); end
  def regexp; end
  def split(uri); end
end
module Gem::URI::Util
  def make_components_hash(klass, array_hash); end
  def self.make_components_hash(klass, array_hash); end
end
module Gem::URI::Schemes
end
class Gem::URI::Error < StandardError
end
class Gem::URI::InvalidURIError < Gem::URI::Error
end
class Gem::URI::InvalidComponentError < Gem::URI::Error
end
class Gem::URI::BadURIError < Gem::URI::Error
end
module Gem
  def URI(uri); end
  def self.URI(uri); end
end
class Gem::URI::Generic
  def +(oth); end
  def -(oth); end
  def ==(oth); end
  def absolute; end
  def absolute?; end
  def check_host(v); end
  def check_opaque(v); end
  def check_password(v, user = nil); end
  def check_path(v); end
  def check_port(v); end
  def check_registry(v); end
  def check_scheme(v); end
  def check_user(v); end
  def check_userinfo(user, password = nil); end
  def coerce(oth); end
  def component; end
  def component_ary; end
  def decoded_password; end
  def decoded_user; end
  def default_port; end
  def eql?(oth); end
  def escape_userpass(v); end
  def find_proxy(env = nil); end
  def fragment; end
  def fragment=(v); end
  def hash; end
  def hierarchical?; end
  def host; end
  def host=(v); end
  def hostname; end
  def hostname=(v); end
  def initialize(scheme, userinfo, host, port, registry, path, opaque, query, fragment, parser = nil, arg_check = nil); end
  def inspect; end
  def merge!(oth); end
  def merge(oth); end
  def merge_path(base, rel); end
  def normalize!; end
  def normalize; end
  def opaque; end
  def opaque=(v); end
  def parser; end
  def password; end
  def password=(password); end
  def path; end
  def path=(v); end
  def port; end
  def port=(v); end
  def query; end
  def query=(v); end
  def registry; end
  def registry=(v); end
  def relative?; end
  def replace!(oth); end
  def route_from(oth); end
  def route_from0(oth); end
  def route_from_path(src, dst); end
  def route_to(oth); end
  def scheme; end
  def scheme=(v); end
  def select(*components); end
  def self.build(args); end
  def self.build2(args); end
  def self.component; end
  def self.default_port; end
  def self.use_proxy?(hostname, addr, port, no_proxy); end
  def self.use_registry; end
  def set_host(v); end
  def set_opaque(v); end
  def set_password(v); end
  def set_path(v); end
  def set_port(v); end
  def set_registry(v); end
  def set_scheme(v); end
  def set_user(v); end
  def set_userinfo(user, password = nil); end
  def split_path(path); end
  def split_userinfo(ui); end
  def to_s; end
  def to_str; end
  def user; end
  def user=(user); end
  def userinfo; end
  def userinfo=(userinfo); end
  include Gem::URI
end
class Gem::URI::File < Gem::URI::Generic
  def check_password(user); end
  def check_user(user); end
  def check_userinfo(user); end
  def self.build(args); end
  def set_host(v); end
  def set_password(v); end
  def set_port(v); end
  def set_user(v); end
  def set_userinfo(v); end
end
class Gem::URI::FTP < Gem::URI::Generic
  def check_typecode(v); end
  def initialize(scheme, userinfo, host, port, registry, path, opaque, query, fragment, parser = nil, arg_check = nil); end
  def merge(oth); end
  def path; end
  def self.build(args); end
  def self.new2(user, password, host, port, path, typecode = nil, arg_check = nil); end
  def set_path(v); end
  def set_typecode(v); end
  def to_s; end
  def typecode; end
  def typecode=(typecode); end
end
class Gem::URI::HTTP < Gem::URI::Generic
  def authority; end
  def origin; end
  def request_uri; end
  def self.build(args); end
end
class Gem::URI::HTTPS < Gem::URI::HTTP
end
class Gem::URI::LDAP < Gem::URI::Generic
  def attributes; end
  def attributes=(val); end
  def build_path_query; end
  def dn; end
  def dn=(val); end
  def extensions; end
  def extensions=(val); end
  def filter; end
  def filter=(val); end
  def hierarchical?; end
  def initialize(*arg); end
  def parse_dn; end
  def parse_query; end
  def scope; end
  def scope=(val); end
  def self.build(args); end
  def set_attributes(val); end
  def set_dn(val); end
  def set_extensions(val); end
  def set_filter(val); end
  def set_scope(val); end
end
class Gem::URI::LDAPS < Gem::URI::LDAP
end
class Gem::URI::MailTo < Gem::URI::Generic
  def check_headers(v); end
  def check_to(v); end
  def headers; end
  def headers=(v); end
  def initialize(*arg); end
  def self.build(args); end
  def set_headers(v); end
  def set_to(v); end
  def to; end
  def to=(v); end
  def to_mailtext; end
  def to_rfc822text; end
  def to_s; end
  include Gem::URI::RFC2396_REGEXP
end
class Gem::URI::WS < Gem::URI::Generic
  def request_uri; end
  def self.build(args); end
end
class Gem::URI::WSS < Gem::URI::WS
end
