# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/sshkit/all/sshkit.rbi
#
# sshkit-1.22.2

class Array
end
class Hash
end
module SSHKit
end
class SSHKit::UnparsableHostStringError < SSHKit::StandardError
end
class SSHKit::Host
end
class SSHKit::SimpleHostParser
end
class SSHKit::HostWithPortParser < SSHKit::SimpleHostParser
end
class SSHKit::HostWithUsernameAndPortParser < SSHKit::SimpleHostParser
end
class SSHKit::IPv6HostWithPortParser < SSHKit::SimpleHostParser
end
class SSHKit::HostWithUsernameParser < SSHKit::SimpleHostParser
end
class SSHKit::Color
end
class SSHKit::Command
end
class SSHKit::Command::Failed < SSHKit::StandardError
end
class SSHKit::CommandMap
end
class SSHKit::CommandMap::CommandHash
end
class SSHKit::CommandMap::PrefixProvider
end
class SSHKit::Configuration
end
class SSHKit::Coordinator
end
class SSHKit::DeprecationLogger
end
module SSHKit::DSL
end
module SSHKit::Runner
end
class SSHKit::Runner::ExecuteError < SSHKit::StandardError
end
class SSHKit::Logger
end
class SSHKit::LogMessage
end
class SSHKit::MappingInteractionHandler
end
module SSHKit::Formatter
end
class SSHKit::Formatter::Abstract
  extend Forwardable
end
class SSHKit::Formatter::BlackHole < SSHKit::Formatter::Abstract
end
class SSHKit::Formatter::Pretty < SSHKit::Formatter::Abstract
end
class SSHKit::Formatter::SimpleText < SSHKit::Formatter::Pretty
end
class SSHKit::Formatter::Dot < SSHKit::Formatter::Abstract
end
class SSHKit::Runner::Abstract
end
class SSHKit::Runner::Sequential < SSHKit::Runner::Abstract
end
class SSHKit::Runner::Parallel < SSHKit::Runner::Abstract
end
class SSHKit::Runner::Group < SSHKit::Runner::Sequential
end
class SSHKit::Runner::Null < SSHKit::Runner::Abstract
end
module SSHKit::Backend
end
class SSHKit::Backend::MethodUnavailableError < SSHKit::StandardError
end
class SSHKit::Backend::Abstract
  extend Forwardable
end
class SSHKit::Backend::ConnectionPool::Cache
end
class Net::SSH::Proxy::Command
end
class SSHKit::Backend::ConnectionPool
end
class SSHKit::Backend::Printer < SSHKit::Backend::Abstract
end
module Net
end
module Net::SSH
end
class Net::SSH::Config
end
class SSHKit::Backend::Netssh < SSHKit::Backend::Abstract
end
class SSHKit::Backend::Netssh::Configuration
end
class SSHKit::Backend::Netssh::KnownHostsKeys
  include Mutex_m
end
class SSHKit::Backend::Netssh::KnownHosts
  include Mutex_m
end
class SSHKit::Backend::Local < SSHKit::Backend::Abstract
end
class SSHKit::Backend::Skipper < SSHKit::Backend::Abstract
end
class SSHKit::StandardError < StandardError
end
module SSHKit::Redaction
end
