# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/webrick/all/webrick.rbi
#
# webrick-1.8.1

module Errno
end
class Errno::EPROTO < SystemCallError
end
class Errno::ECONNRESET < SystemCallError
end
class Errno::ECONNABORTED < SystemCallError
end
module WEBrick
end
class WEBrick::HTTPVersion
  include Comparable
end
module WEBrick::HTTPUtils
end
class WEBrick::HTTPUtils::FormData < String
end
module WEBrick::Utils
end
class WEBrick::Utils::TimeoutHandler
  extend Singleton::SingletonClassMethods
  include Singleton
end
class WEBrick::BasicLog
end
class WEBrick::Log < WEBrick::BasicLog
end
module WEBrick::Config
end
class WEBrick::ServerError < StandardError
end
class WEBrick::SimpleServer
end
class WEBrick::Daemon
end
class WEBrick::GenericServer
end
module WEBrick::AccessLog
end
class WEBrick::AccessLog::AccessLogError < StandardError
end
module WEBrick::HTMLUtils
end
class WEBrick::Cookie
end
module WEBrick::HTTPStatus
end
class WEBrick::HTTPStatus::Status < StandardError
end
class WEBrick::HTTPStatus::Info < WEBrick::HTTPStatus::Status
end
class WEBrick::HTTPStatus::Success < WEBrick::HTTPStatus::Status
end
class WEBrick::HTTPStatus::Redirect < WEBrick::HTTPStatus::Status
end
class WEBrick::HTTPStatus::Error < WEBrick::HTTPStatus::Status
end
class WEBrick::HTTPStatus::ClientError < WEBrick::HTTPStatus::Error
end
class WEBrick::HTTPStatus::ServerError < WEBrick::HTTPStatus::Error
end
class WEBrick::HTTPStatus::EOFError < StandardError
end
class WEBrick::HTTPStatus::Continue < WEBrick::HTTPStatus::Info
end
class WEBrick::HTTPStatus::SwitchingProtocols < WEBrick::HTTPStatus::Info
end
class WEBrick::HTTPStatus::OK < WEBrick::HTTPStatus::Success
end
class WEBrick::HTTPStatus::Created < WEBrick::HTTPStatus::Success
end
class WEBrick::HTTPStatus::Accepted < WEBrick::HTTPStatus::Success
end
class WEBrick::HTTPStatus::NonAuthoritativeInformation < WEBrick::HTTPStatus::Success
end
class WEBrick::HTTPStatus::NoContent < WEBrick::HTTPStatus::Success
end
class WEBrick::HTTPStatus::ResetContent < WEBrick::HTTPStatus::Success
end
class WEBrick::HTTPStatus::PartialContent < WEBrick::HTTPStatus::Success
end
class WEBrick::HTTPStatus::MultiStatus < WEBrick::HTTPStatus::Success
end
class WEBrick::HTTPStatus::MultipleChoices < WEBrick::HTTPStatus::Redirect
end
class WEBrick::HTTPStatus::MovedPermanently < WEBrick::HTTPStatus::Redirect
end
class WEBrick::HTTPStatus::Found < WEBrick::HTTPStatus::Redirect
end
class WEBrick::HTTPStatus::SeeOther < WEBrick::HTTPStatus::Redirect
end
class WEBrick::HTTPStatus::NotModified < WEBrick::HTTPStatus::Redirect
end
class WEBrick::HTTPStatus::UseProxy < WEBrick::HTTPStatus::Redirect
end
class WEBrick::HTTPStatus::TemporaryRedirect < WEBrick::HTTPStatus::Redirect
end
class WEBrick::HTTPStatus::BadRequest < WEBrick::HTTPStatus::ClientError
end
class WEBrick::HTTPStatus::Unauthorized < WEBrick::HTTPStatus::ClientError
end
class WEBrick::HTTPStatus::PaymentRequired < WEBrick::HTTPStatus::ClientError
end
class WEBrick::HTTPStatus::Forbidden < WEBrick::HTTPStatus::ClientError
end
class WEBrick::HTTPStatus::NotFound < WEBrick::HTTPStatus::ClientError
end
class WEBrick::HTTPStatus::MethodNotAllowed < WEBrick::HTTPStatus::ClientError
end
class WEBrick::HTTPStatus::NotAcceptable < WEBrick::HTTPStatus::ClientError
end
class WEBrick::HTTPStatus::ProxyAuthenticationRequired < WEBrick::HTTPStatus::ClientError
end
class WEBrick::HTTPStatus::RequestTimeout < WEBrick::HTTPStatus::ClientError
end
class WEBrick::HTTPStatus::Conflict < WEBrick::HTTPStatus::ClientError
end
class WEBrick::HTTPStatus::Gone < WEBrick::HTTPStatus::ClientError
end
class WEBrick::HTTPStatus::LengthRequired < WEBrick::HTTPStatus::ClientError
end
class WEBrick::HTTPStatus::PreconditionFailed < WEBrick::HTTPStatus::ClientError
end
class WEBrick::HTTPStatus::RequestEntityTooLarge < WEBrick::HTTPStatus::ClientError
end
class WEBrick::HTTPStatus::RequestURITooLarge < WEBrick::HTTPStatus::ClientError
end
class WEBrick::HTTPStatus::UnsupportedMediaType < WEBrick::HTTPStatus::ClientError
end
class WEBrick::HTTPStatus::RequestRangeNotSatisfiable < WEBrick::HTTPStatus::ClientError
end
class WEBrick::HTTPStatus::ExpectationFailed < WEBrick::HTTPStatus::ClientError
end
class WEBrick::HTTPStatus::UnprocessableEntity < WEBrick::HTTPStatus::ClientError
end
class WEBrick::HTTPStatus::Locked < WEBrick::HTTPStatus::ClientError
end
class WEBrick::HTTPStatus::FailedDependency < WEBrick::HTTPStatus::ClientError
end
class WEBrick::HTTPStatus::UpgradeRequired < WEBrick::HTTPStatus::ClientError
end
class WEBrick::HTTPStatus::PreconditionRequired < WEBrick::HTTPStatus::ClientError
end
class WEBrick::HTTPStatus::TooManyRequests < WEBrick::HTTPStatus::ClientError
end
class WEBrick::HTTPStatus::RequestHeaderFieldsTooLarge < WEBrick::HTTPStatus::ClientError
end
class WEBrick::HTTPStatus::UnavailableForLegalReasons < WEBrick::HTTPStatus::ClientError
end
class WEBrick::HTTPStatus::InternalServerError < WEBrick::HTTPStatus::ServerError
end
class WEBrick::HTTPStatus::NotImplemented < WEBrick::HTTPStatus::ServerError
end
class WEBrick::HTTPStatus::BadGateway < WEBrick::HTTPStatus::ServerError
end
class WEBrick::HTTPStatus::ServiceUnavailable < WEBrick::HTTPStatus::ServerError
end
class WEBrick::HTTPStatus::GatewayTimeout < WEBrick::HTTPStatus::ServerError
end
class WEBrick::HTTPStatus::HTTPVersionNotSupported < WEBrick::HTTPStatus::ServerError
end
class WEBrick::HTTPStatus::InsufficientStorage < WEBrick::HTTPStatus::ServerError
end
class WEBrick::HTTPStatus::NetworkAuthenticationRequired < WEBrick::HTTPStatus::ServerError
end
class WEBrick::HTTPRequest
end
class WEBrick::HTTPResponse
end
class WEBrick::HTTPResponse::InvalidHeader < StandardError
end
class WEBrick::HTTPResponse::ChunkedWrapper
end
module WEBrick::HTTPServlet
end
class WEBrick::HTTPServlet::HTTPServletError < StandardError
end
class WEBrick::HTTPServlet::AbstractServlet
end
class WEBrick::HTTPServlet::DefaultFileHandler < WEBrick::HTTPServlet::AbstractServlet
end
class WEBrick::HTTPServlet::FileHandler < WEBrick::HTTPServlet::AbstractServlet
end
class WEBrick::HTTPServlet::CGIHandler < WEBrick::HTTPServlet::AbstractServlet
end
class WEBrick::HTTPServlet::ERBHandler < WEBrick::HTTPServlet::AbstractServlet
end
class WEBrick::HTTPServlet::ProcHandler < WEBrick::HTTPServlet::AbstractServlet
end
class WEBrick::HTTPServerError < WEBrick::ServerError
end
class WEBrick::HTTPServer < WEBrick::GenericServer
end
class WEBrick::HTTPServer::MountTable
end
module WEBrick::HTTPAuth
end
module WEBrick::HTTPAuth::Authenticator
end
module WEBrick::HTTPAuth::ProxyAuthenticator
end
class WEBrick::HTTPAuth::BasicAuth
  include WEBrick::HTTPAuth::Authenticator
end
class WEBrick::HTTPAuth::ProxyBasicAuth < WEBrick::HTTPAuth::BasicAuth
  include WEBrick::HTTPAuth::ProxyAuthenticator
end
class WEBrick::HTTPAuth::DigestAuth
  include WEBrick::HTTPAuth::Authenticator
end
class WEBrick::HTTPAuth::ProxyDigestAuth < WEBrick::HTTPAuth::DigestAuth
  include WEBrick::HTTPAuth::ProxyAuthenticator
end
module WEBrick::HTTPAuth::UserDB
end
class WEBrick::HTTPAuth::Htpasswd
  include WEBrick::HTTPAuth::UserDB
end
class WEBrick::HTTPAuth::Htdigest
  include WEBrick::HTTPAuth::UserDB
end
class WEBrick::HTTPAuth::Htgroup
end
