inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-performance
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.4.2
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'bin/*'
    - 'vendor/**/*'

Rails:
  Enabled: true
  
Rails/I18nLocaleTexts:
  Enabled: false

Layout/LineLength:
  Max: 100

Metrics/BlockLength:
  Max: 100
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'

Metrics/MethodLength:
  Max: 55

Metrics/ClassLength:
  Max: 200

Style/Documentation:
  Enabled: false
