source 'https://rubygems.org'
ruby '2.4.1'

gem 'rails', '5.1'
gem 'devise', git: 'https://github.com/plataformatec/devise.git'
gem 'pg'
gem 'rack'
gem 'railties'
gem 'coffee-rails'
gem 'uglifier'
gem 'jquery-turbolinks'
gem 'turbolinks'
gem 'bootstrap-sass'
gem 'autoprefixer-rails'
gem 'sass-rails'
gem 'therubyracer',  platforms: :ruby
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'jbuilder'
gem 'simple_form', :git => 'https://github.com/elsurudo/simple_form', branch: 'rails-5.1.0'
gem 'momentjs-rails'
gem 'bootstrap3-datetimepicker-rails'
gem 'ckeditor', :git => 'https://github.com/galetahub/ckeditor'
gem 'bcrypt'
gem 'attachinary', :git => 'https://github.com/ThomasConnolly/attachinary'
gem 'cloudinary'
gem 'jquery-fileupload-rails'
gem 'remotipart'
gem 'actionmailer'
gem 'premailer-rails'
gem 'nokogiri'
gem 'httparty'
gem 'stripe', :git => 'https://github.com/stripe/stripe-ruby'
gem 'bootstrap-will_paginate'
gem 'foreman'
gem 'puma'
gem 'birthday'
gem 'rolify'
gem 'figaro'
gem 'capybara'
gem 'regressor'
#gem 'zoom', :git => 'https://github.com/bricestacey/ruby-zoom'

group :development do
  gem 'meta_request'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'annotate'
  gem 'awesome_print'
  gem 'byebug'
  gem 'rubycritic'
end

group :development, :test do
  gem 'guard'
  gem 'guard-livereload'
  gem 'pry-rails'
  gem 'pry-byebug'
  gem 'pry-stack_explorer'
  gem 'pry-doc'
  gem 'spring'
  gem 'factory_girl_rails'
  gem 'simple_bdd'
  gem 'letter_opener'
  gem 'email_spec'
  gem 'rspec-rails'
end

group :test do
  gem 'shoulda-matchers'
  gem 'faker'
  gem 'database_cleaner'
end

gem 'webpacker'
gem 'rails_on_heroku'
