source 'https://rubygems.org'
ruby '2.5.3'

gem 'rails', '5.2.2'
gem 'devise'
gem 'pg', '~> 0.18.4'
gem 'rack'
gem 'railties'
gem 'font-awesome-rails'
gem 'coffee-rails'
gem 'uglifier'
gem 'jquery-turbolinks'
gem 'turbolinks'
gem 'sprockets-rails', require: 'sprockets/railtie'
gem 'bootstrap'
gem 'autoprefixer-rails'
gem 'sass-rails'
gem 'mini_racer'
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'jbuilder'
gem 'nivo-rails'
gem 'momentjs-rails'
gem 'bootstrap-datepicker-rails'
gem 'popper_js'
gem 'ckeditor', :git => 'https://github.com/galetahub/ckeditor'
gem 'bcrypt'
gem 'attachinary', :git => 'https://github.com/ThomasConnolly/attachinary'
gem 'cloudinary'
gem 'jquery-fileupload-rails'
gem 'remotipart'
gem 'actionmailer'
gem 'premailer-rails'
gem 'mail'
gem 'nokogiri'
gem 'redis'
gem 'httparty'
gem 'stripe'
gem 'stripe_event'
gem 'bootstrap-will_paginate'
gem 'puma'
gem 'bootsnap', require: false
gem 'birthday'
gem 'rolify'
gem 'figaro'
gem 'googlebooks'
gem 'openlibrary'
gem 'rest-client'
gem 'rspec-rails'
gem 'pry'
gem 'pry-rails'
gem 'pry-awesome_print'
gem 'awesome_print'
gem 'simple_form', '4.0.1'
gem 'mini_magick'
gem 'aws-sdk-s3', require: false

group :development do
  gem 'meta_request'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'annotate'
  gem 'byebug'
  gem 'capistrano'
  gem 'web-console'
  gem 'listen'
end

group :development, :test do
  gem 'guard'
  gem 'guard-livereload'
  gem 'pry-byebug'
  gem 'pry-stack_explorer'
  gem 'pry-doc'
  gem 'spring'
  gem 'spring-watcher-listen'
  gem 'factory_bot_rails'
  gem 'letter_opener'
  gem 'email_spec'
  gem 'shoulda-matchers'
end

group :test do
  gem 'capybara'
  gem 'faker'
  gem 'database_cleaner'
  gem 'selenium-webdriver'
  gem 'chromedriver-helper'
end

gem 'rails_on_heroku'
