source 'https://rubygems.org'
ruby '2.3.1'

gem 'rails', '4.2.7'
gem 'pg'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'twitter-bootstrap-rails'
gem 'turbolinks', '~> 5.0.0.beta'
gem 'jquery-turbolinks'
gem 'bootstrap-sass'
gem 'autoprefixer-rails'
gem 'sass-rails', '~> 5.0', '>= 5.0.4'
gem 'therubyracer',  platforms: :ruby
gem 'jquery-rails'
gem 'jquery-slick-rails'
gem 'jquery-hotkeys-rails'
gem 'jquery-ui-rails'
gem 'jbuilder', '~> 2.0'
gem 'jquery-fileupload-rails'
gem 'simple_form'
gem 'ckeditor'
gem 'bcrypt'
gem 'cloudinary'
gem 'attachinary'
gem 'remotipart'
gem 'sidekiq'
gem 'actionmailer'
gem 'premailer-rails'
gem 'nokogiri'
gem 'social-share-button'
gem 'httparty'
gem 'stripe', :git => 'https://github.com/stripe/stripe-ruby'
gem 'bootstrap-will_paginate'
gem 'devise'
gem 'devise_invitable'
gem 'puma'
gem 'foreman'
gem 'birthday'
gem 'rolify'

group :development do
  gem 'meta_request'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'quiet_assets'
  gem 'annotate'
  gem 'awesome_print'
  gem 'byebug'
  gem 'rubycritic'
end

group :development, :test do
  gem 'guard'
  gem 'guard-livereload'
  gem 'guard-rspec'
  gem 'pry-rails'
  gem 'pry-byebug'
  gem 'pry-stack_explorer'
  gem 'rspec'
  gem 'rspec-rails'
  gem 'spring'
  gem 'capybara'
  gem 'factory_girl_rails'
  gem 'simple_bdd'
  gem 'shoulda-matchers'
  gem 'database_cleaner'
  gem 'letter_opener'
  gem 'email_spec'
end

group :test do
  gem 'ffaker'
  gem 'capybara-webkit'
  gem 'launchy'
end

group :production do
  gem 'rails_12factor'
end