# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `MemberMailer`.
# Please instead update this file by running `bin/tapioca dsl MemberMailer`.

class MemberMailer; end
