# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `PostMailer`.
# Please instead update this file by running `bin/tapioca dsl PostMailer`.

class PostMailer
  class << self
    sig { params(post: T.untyped).returns(::ActionMailer::MessageDelivery) }
    def post_created(post); end
  end
end
