# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `StoryIdeaMailer`.
# Please instead update this file by running `bin/tapioca dsl StoryIdeaMailer`.

class StoryIdeaMailer
  class << self
    sig { params(story_idea: T.untyped).returns(::ActionMailer::MessageDelivery) }
    def story_idea_created(story_idea); end
  end
end
