# typed: strict

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `StripeMailer`.
# Please instead update this file by running `bin/tapioca dsl StripeMailer`.

class StripeMailer
  class << self
    sig { params(stripe_report: T.untyped).returns(::ActionMailer::MessageDelivery) }
    def report_created(stripe_report); end
  end
end
