# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `TicketMailer`.
# Please instead update this file by running `bin/tapioca dsl TicketMailer`.

class TicketMailer
  class << self
    sig { params(ticket: T.untyped).returns(::ActionMailer::MessageDelivery) }
    def thanks(ticket); end
  end
end
