# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `VnoteMailer`.
# Please instead update this file by running `bin/tapioca dsl VnoteMailer`.

class VnoteMailer
  class << self
    sig { params(vnote: T.untyped).returns(::ActionMailer::MessageDelivery) }
    def vnote_created(vnote); end
  end
end
