# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/pathways', type: :request do
  # Pathway. As you add validations to Pathway, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      Pathway.create! valid_attributes
      get pathways_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      pathway = Pathway.create! valid_attributes
      get pathway_url(pathway)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_pathway_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'render a successful response' do
      pathway = Pathway.create! valid_attributes
      get edit_pathway_url(pathway)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Pathway' do
        expect do
          post pathways_url, params: { pathway: valid_attributes }
        end.to change(Pathway, :count).by(1)
      end

      it 'redirects to the created pathway' do
        post pathways_url, params: { pathway: valid_attributes }
        expect(response).to redirect_to(pathway_url(Pathway.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Pathway' do
        expect do
          post pathways_url, params: { pathway: invalid_attributes }
        end.to change(Pathway, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post pathways_url, params: { pathway: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested pathway' do
        pathway = Pathway.create! valid_attributes
        patch pathway_url(pathway), params: { pathway: new_attributes }
        pathway.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the pathway' do
        pathway = Pathway.create! valid_attributes
        patch pathway_url(pathway), params: { pathway: new_attributes }
        pathway.reload
        expect(response).to redirect_to(pathway_url(pathway))
      end
    end

    context 'with invalid parameters' do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        pathway = Pathway.create! valid_attributes
        patch pathway_url(pathway), params: { pathway: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested pathway' do
      pathway = Pathway.create! valid_attributes
      expect do
        delete pathway_url(pathway)
      end.to change(Pathway, :count).by(-1)
    end

    it 'redirects to the pathways list' do
      pathway = Pathway.create! valid_attributes
      delete pathway_url(pathway)
      expect(response).to redirect_to(pathways_url)
    end
  end
end
