# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/pray_fors', type: :request do
  # PrayFor. As you add validations to PrayFor, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      PrayFor.create! valid_attributes
      get pray_fors_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      pray_for = PrayFor.create! valid_attributes
      get pray_for_url(pray_for)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_pray_for_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'render a successful response' do
      pray_for = PrayFor.create! valid_attributes
      get edit_pray_for_url(pray_for)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new PrayFor' do
        expect do
          post pray_fors_url, params: { pray_for: valid_attributes }
        end.to change(PrayFor, :count).by(1)
      end

      it 'redirects to the created pray_for' do
        post pray_fors_url, params: { pray_for: valid_attributes }
        expect(response).to redirect_to(pray_for_url(PrayFor.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new PrayFor' do
        expect do
          post pray_fors_url, params: { pray_for: invalid_attributes }
        end.to change(PrayFor, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post pray_fors_url, params: { pray_for: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested pray_for' do
        pray_for = PrayFor.create! valid_attributes
        patch pray_for_url(pray_for), params: { pray_for: new_attributes }
        pray_for.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the pray_for' do
        pray_for = PrayFor.create! valid_attributes
        patch pray_for_url(pray_for), params: { pray_for: new_attributes }
        pray_for.reload
        expect(response).to redirect_to(pray_for_url(pray_for))
      end
    end

    context 'with invalid parameters' do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        pray_for = PrayFor.create! valid_attributes
        patch pray_for_url(pray_for), params: { pray_for: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested pray_for' do
      pray_for = PrayFor.create! valid_attributes
      expect do
        delete pray_for_url(pray_for)
      end.to change(PrayFor, :count).by(-1)
    end

    it 'redirects to the pray_fors list' do
      pray_for = PrayFor.create! valid_attributes
      delete pray_for_url(pray_for)
      expect(response).to redirect_to(pray_fors_url)
    end
  end
end
