 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/reserve_slots", type: :request do
  
  # ReserveSlot. As you add validations to ReserveSlot, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ReserveSlot.create! valid_attributes
      get reserve_slots_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      reserve_slot = ReserveSlot.create! valid_attributes
      get reserve_slot_url(reserve_slot)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_reserve_slot_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      reserve_slot = ReserveSlot.create! valid_attributes
      get edit_reserve_slot_url(reserve_slot)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ReserveSlot" do
        expect {
          post reserve_slots_url, params: { reserve_slot: valid_attributes }
        }.to change(ReserveSlot, :count).by(1)
      end

      it "redirects to the created reserve_slot" do
        post reserve_slots_url, params: { reserve_slot: valid_attributes }
        expect(response).to redirect_to(reserve_slot_url(ReserveSlot.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ReserveSlot" do
        expect {
          post reserve_slots_url, params: { reserve_slot: invalid_attributes }
        }.to change(ReserveSlot, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post reserve_slots_url, params: { reserve_slot: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested reserve_slot" do
        reserve_slot = ReserveSlot.create! valid_attributes
        patch reserve_slot_url(reserve_slot), params: { reserve_slot: new_attributes }
        reserve_slot.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the reserve_slot" do
        reserve_slot = ReserveSlot.create! valid_attributes
        patch reserve_slot_url(reserve_slot), params: { reserve_slot: new_attributes }
        reserve_slot.reload
        expect(response).to redirect_to(reserve_slot_url(reserve_slot))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        reserve_slot = ReserveSlot.create! valid_attributes
        patch reserve_slot_url(reserve_slot), params: { reserve_slot: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested reserve_slot" do
      reserve_slot = ReserveSlot.create! valid_attributes
      expect {
        delete reserve_slot_url(reserve_slot)
      }.to change(ReserveSlot, :count).by(-1)
    end

    it "redirects to the reserve_slots list" do
      reserve_slot = ReserveSlot.create! valid_attributes
      delete reserve_slot_url(reserve_slot)
      expect(response).to redirect_to(reserve_slots_url)
    end
  end
end
