require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/story_assignments", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # StoryAssignment. As you add validations to StoryAssignment, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      StoryAssignment.create! valid_attributes
      get story_assignments_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      story_assignment = StoryAssignment.create! valid_attributes
      get story_assignment_url(story_assignment)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_story_assignment_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      story_assignment = StoryAssignment.create! valid_attributes
      get edit_story_assignment_url(story_assignment)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new StoryAssignment" do
        expect {
          post story_assignments_url, params: { story_assignment: valid_attributes }
        }.to change(StoryAssignment, :count).by(1)
      end

      it "redirects to the created story_assignment" do
        post story_assignments_url, params: { story_assignment: valid_attributes }
        expect(response).to redirect_to(story_assignment_url(StoryAssignment.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new StoryAssignment" do
        expect {
          post story_assignments_url, params: { story_assignment: invalid_attributes }
        }.to change(StoryAssignment, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post story_assignments_url, params: { story_assignment: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested story_assignment" do
        story_assignment = StoryAssignment.create! valid_attributes
        patch story_assignment_url(story_assignment), params: { story_assignment: new_attributes }
        story_assignment.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the story_assignment" do
        story_assignment = StoryAssignment.create! valid_attributes
        patch story_assignment_url(story_assignment), params: { story_assignment: new_attributes }
        story_assignment.reload
        expect(response).to redirect_to(story_assignment_url(story_assignment))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        story_assignment = StoryAssignment.create! valid_attributes
        patch story_assignment_url(story_assignment), params: { story_assignment: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested story_assignment" do
      story_assignment = StoryAssignment.create! valid_attributes
      expect {
        delete story_assignment_url(story_assignment)
      }.to change(StoryAssignment, :count).by(-1)
    end

    it "redirects to the story_assignments list" do
      story_assignment = StoryAssignment.create! valid_attributes
      delete story_assignment_url(story_assignment)
      expect(response).to redirect_to(story_assignments_url)
    end
  end
end
