require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/submit_stories", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # SubmitStory. As you add validations to SubmitStory, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      SubmitStory.create! valid_attributes
      get submit_stories_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      submit_story = SubmitStory.create! valid_attributes
      get submit_story_url(submit_story)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_submit_story_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      submit_story = SubmitStory.create! valid_attributes
      get edit_submit_story_url(submit_story)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new SubmitStory" do
        expect {
          post submit_stories_url, params: { submit_story: valid_attributes }
        }.to change(SubmitStory, :count).by(1)
      end

      it "redirects to the created submit_story" do
        post submit_stories_url, params: { submit_story: valid_attributes }
        expect(response).to redirect_to(submit_story_url(SubmitStory.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new SubmitStory" do
        expect {
          post submit_stories_url, params: { submit_story: invalid_attributes }
        }.to change(SubmitStory, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post submit_stories_url, params: { submit_story: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested submit_story" do
        submit_story = SubmitStory.create! valid_attributes
        patch submit_story_url(submit_story), params: { submit_story: new_attributes }
        submit_story.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the submit_story" do
        submit_story = SubmitStory.create! valid_attributes
        patch submit_story_url(submit_story), params: { submit_story: new_attributes }
        submit_story.reload
        expect(response).to redirect_to(submit_story_url(submit_story))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        submit_story = SubmitStory.create! valid_attributes
        patch submit_story_url(submit_story), params: { submit_story: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested submit_story" do
      submit_story = SubmitStory.create! valid_attributes
      expect {
        delete submit_story_url(submit_story)
      }.to change(SubmitStory, :count).by(-1)
    end

    it "redirects to the submit_stories list" do
      submit_story = SubmitStory.create! valid_attributes
      delete submit_story_url(submit_story)
      expect(response).to redirect_to(submit_stories_url)
    end
  end
end
