---
development:
  cloud_name: "saintpaulsnaples-org"
  api_key: '521449493132342'
  api_secret: 7XGlmOUSCW7Hm-O60V0WSmUnGxc
  enhance_image_tag: true
  static_image_support: true
production:
  cloud_name: "saintpaulsnaples-org"
  api_key: '521449493132342'
  api_secret: 7XGlmOUSCW7Hm-O60V0WSmUnGxc
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: "saintpaulsnaples-org"
  api_key: '521449493132342'
  api_secret: 7XGlmOUSCW7Hm-O60V0WSmUnGxc
  enhance_image_tag: true
  static_image_support: false

#Base delivery URL:  http://res.cloudinary.com/saintpaulsnaples-org ▼
#Secure delivery URL:  https://res.cloudinary.com/saintpaulsnaples-org ▼
#API Base URL: https://api.cloudinary.com/v1_1/saintpaulsnaples-org ▼
