default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  primary:
    <<: *default
    database: paul_development
    username: postgres
    password: tommycon
    host: localhost

test:
  <<: *default
  database: paul_test
  username: postgres
  password: tommycon
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV['DATABASE_URL'] %>