toolbar: 
  - insertfile undo redo | styleselect | bold italic
  - alignleft aligncenter alignright alignjustify
  - bullist numlist outdent indent | link image

plugins: 
  - link 
  - image
  - searchreplace 
  - code
  - paste
