email_list:
- first_name: Fr. Tom
- last_name: Fr.Tom
  email: Fr.Tom@saintpaulsnaples.org
- first_name: Diane 
  last_name: Augustus
  email: daug6978@sbcglobal.net
- first_name: Jack 
  last_name: LaRose  
  email: fd166larose@gmail.com
- first_name: Jeannie 
  last_name: Smith
  email: jewiggles@yahoo.com
- first_name: Julio 
  last_name: Albino
  email: jualbin@optonline.net
- first_name: Mary Lou 
  last_name: Dogoloff
  email: midogo@me.com 
- first_name: Paul 
  last_name: Nelson
  email: paulnelsonsr@gmail.com
- first_name: Rosemary 
  last_name: Porembo
  email: rkp44@hotmail.com
- first name: Murray 
  last_name: Smith
  email: murray_smith10@comcast.net
- first_name: Tom 
  last_name: Connolly
  email: tom.connolly@comcast.net
- first_name: Betty 
  last_name: Hernandez
  email: welcome@saintpaulsnaples.org
