email_list:
- name: Fr. Tom
  email: Fr.Tom@saintpaulsnaples.org
- name: Diane Augustus
  email: daug6978@sbcglobal.net
- name: Rose Porembo  
  email: fd166larose@gmail.com
- name: Jeannie Smith
  email: jewiggles@yahoo.com
- name: Julio Albino
  email: jualbin@optonline.net
- name: Mary Lou Dogoloff
  email: midogo@me.com 
- name: Paul Nelson
  email: paulnelsonsr@gmail.com
- name: Rosemary Porembo
  email: rkp831@hotmail.com
- name: Murray Smith
  email: murray_smith10@comcast.net
- name: Tom Connolly
  email: tom.connolly@comcast.net
- name: Betty Hernandez
  email: welcome@saintpaulsnaples.org